#if !canImport(ObjectiveC)
import XCTest

extension SwiftArrayInitializationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftArrayInitializationsTests = [
        ("testRepeating", testRepeating),
        ("testReserveCapacity", testReserveCapacity),
        ("testUninitialized", testUninitialized),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftArrayInitializationsTests.__allTests__SwiftArrayInitializationsTests),
    ]
}
#endif
